### ISSUE TITLE
Issue 8/5/2020

### ISSUE THREAD

**Issue by eliasecasta** [jessicafarias/jessicafarias#1]
Hello Jessica, I found a really interesting error in your readme that needs to be fixed asap in order for me to sleep well today.

On line 8, column 7 you have inserted an 'e' instead of an 'a'. I would kindly appreciate if you could please fix this error.

Without anything else to say, I wish you the best in this course, keep going, never give up and I hope that we can be partners again in the near future.

- Elias Castañeda, IT Engineer and Full Stack Web Developer member of the team-122-the-manx, Happy coding! 🚀

**Comment by jessicafarias** [comment]
Thank you very much, Elias, I didn't realize about this big mistake however it's already fixed, I will work to continue improving my grammar skills. It could be great if we work together again, let me know if you have some projects in mind.

**Comment by eliasecasta** [comment]
It's my pleasure, Jessica. One more thing though... (let's call this an issue of the issue) "I didn't realize about this big mistake, however" would sound much better if it was written like this: "I was not aware of this big mistake, however...". 

Elias Castañeda, IT Engineer and Full Stack Web Developer member of the team-122-the-manx, Happy coding! 🚀
